name: Buildgram

on:
  workflow_dispatch:
  push:

jobs:
  build:
    permissions:
      contents: write
      packages: write
      pull-requests: read

    name: Build all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v4
        with:
          repository: AyuGram/AyuGramDesktop
          submodules: true
          path: tdesktop
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: prepare packages
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-poetry python-is-python3 python3-venv python3-pip
          python3 -m venv .venv
          source .venv/bin/activate
          pip3 install poetry

      - name: prepare build
        run: |
          source .venv/bin/activate
          ./tdesktop/Telegram/build/prepare/linux.sh

      - name: build tg
        run: |
          source .venv/bin/activate
          cd tdesktop
          docker run --rm -it \
           -v "$PWD:/usr/src/tdesktop" \
           tdesktop:centos_env \
           /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh \
           -D TDESKTOP_API_ID=2040 \
           -D TDESKTOP_API_HASH=b18441a1ff607e10a989891a5462e627

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: os_build
          path: out/*
          compression-level: 9
          if-no-files-found: error
